nelmio_cors:
  defaults:
    allow_credentials: false
    allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
    allow_headers: ['Content-Type','Authorization','X-Requested-With']
    allow_methods: ['GET','POST','PUT','PATCH','DELETE','OPTIONS']
    max_age: 3600
  paths:
    '^/': ~
