name: Enforce repo settings

on:
    push:
        paths:
            - '.github/settings.yml'
            - '.github/workflows/repo-settings.yml'
    workflow_dispatch:
    schedule:
        - cron: '0 3 * * *'  # nightly

permissions:
    contents: read
    administration: write  # needed to manage branch protection & repo settings
    actions: read
    security-events: read

jobs:
    apply:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Run probot-settings
              uses: elstudio/actions-settings@v2
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
